### ISSUE TITLE
为什么我的模拟器还有小米都安装不了这个apk？4.0的系统不行吗

### ISSUE THREAD

**Issue by superhyn** [codeestX/GeekNews#11]

**Comment by codeestX** [comment]
@superhyn 你好，目前设定的Android最低版本是5.0 #1

**Comment by superhyn** [comment]
本人是安卓初学者，那么可以不可以改一段代码就能在4.0上安装？

**Comment by codeestX** [comment]
@superhyn 建议用Android Studio自带的5.0以上版本的模拟器

**Comment by superhyn** [comment]
你好，我已安装，但是数据加载失败是为什么

**Comment by codeestX** [comment]
@superhyn 先排查下模拟器能不能正常上网，再用浏览器测试下访问API能不能取到结果

**Comment by superhyn** [comment]
@codeestX 谢谢，已解决
