### ISSUE TITLE
GeekNews:app:unspecified > net.opacapp:multiline-collapsingtoolbar:1.2.2

### ISSUE THREAD

**Issue by zeshaoaaa** [codeestX/GeekNews#12]
```
Error:Could not find com.android.support:design:24.1.1.
Required by:
    GeekNews:app:unspecified
    GeekNews:app:unspecified > net.opacapp:multiline-collapsingtoolbar:1.2.2

Please install the Android Support Repository from the Android SDK Manager.
<a href="openAndroidSdkManager">Open Android SDK Manager</a>
```

**Comment by codeestX** [comment]
@zeshaoaaa Hello. The current version 1.2.2 of the multiline-collapsingtoolbar library is based on the code from the Design Support Library version 24.1.1.  Make sure your Design Support Library version is 24.1.1 or above.
![image](https://cloud.githubusercontent.com/assets/12326467/18816001/4b4befa0-8372-11e6-912e-35cf93b3550d.png)

**Comment by zeshaoaaa** [comment]
@codeestX 哈哈，这么晚还没睡啊。我觉得你的这个项目最屌的就是用泛型做的Presenter，相比之下谷歌自己推荐的architecture sample实在是弱爆了

**Comment by zeshaoaaa** [comment]
请问怎么确认我的Designe库高于24.1.1呢？我刚下了Nougat（7.0）试了下，还是不行

**Comment by codeestX** [comment]
@zeshaoaaa 这个思路是参考[hot](https://github.com/zj-wukewei/Hot)这个开源项目的，我也觉得这块处理的很赞，就用到自己的项目中了

**Comment by codeestX** [comment]
@zeshaoaaa 你的android sdk目录\extras\android\support\appcompat-v7目录下能看到本地有没有24.1.1以上的版本

**Comment by zeshaoaaa** [comment]
@codeestX 原来是这样，不过你的确花了挺多心思去优化的，所以是你让Hot发扬光大的哈哈。

**Comment by zeshaoaaa** [comment]
@codeestX 的确只有24.0.0-beta1，可能是被墙了没下到24.1.1
