### ISSUE TITLE
使用Android Studio 2.2版本重新编译，自动生成的测试代码出现错误

### ISSUE THREAD

**Issue by TakanashiHitomi** [codeestX/GeekNews#13]
作者你好，我今天刚刚fork了你的代码，使用了Android Studio 2.2 版本编译了一次，但是编译失败了，显示出错的地方是测试的位置，请问是什么情况？

更改处如下：
`buildToolsVersion "24.0.1" -> buildToolsVersion "24.0.2"`

`classpath 'com.android.tools.build:gradle:2.2.0-rc1
' -> classpath 'com.android.tools.build:gradle:2.2.0'`

错误如下：

> Error:(4, 28) 错误: 程序包android.support.test不存在
> Error:(5, 35) 错误: 程序包android.support.test.runner不存在
> Error:(7, 24) 错误: 程序包org.junit.runner不存在
> Error:(8, 30) 错误: 程序包org.testng.annotations不存在
> Error:(17, 2) 错误: 找不到符号
> 符号: 类 RunWith
> Error:(19, 6) 错误: 找不到符号
> 符号:   类 Test
> 位置: 类 ExampleInstrumentedTest
> Error:Execution failed for task ':app:compileGoogleDebugAndroidTestJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by TakanashiHitomi** [comment]
参考了[stackoverflow上的帖子](http://stackoverflow.com/questions/28999124/resolved-versions-for-app-22-0-0-and-test-app-21-0-3-differ)，在`app/build.gradle`中加入以下代码

``` java

configurations.all {
    resolutionStrategy {
        force 'com.android.support:support-annotations:23.1.1'
    }
}

dependencies {
// test
    androidTestCompile 'com.android.support.test:runner:0.5'
    // Set this dependency to use JUnit 4 rules
    androidTestCompile 'com.android.support.test:rules:0.5'
    // Set this dependency to build and run UI Automator tests
    androidTestCompile 'com.android.support.test.uiautomator:uiautomator-v18:2.1.2'
}
```

编译即可通过，似乎是新的自动化测试版本的原因，抱歉打扰作者了
P.S.添加的代码来自https://github.com/JakeWharton/u2020/blob/05a57bf43b9b61f16d32cbe8717af77cd608b0fb/build.gradle#L136-L140

**Comment by codeestX** [comment]
@takanashi-hitomi 你好，感谢反馈，我现在把这些库加上 ^ ^
