### ISSUE TITLE
我导入AS有问题

### ISSUE THREAD

**Issue by lpslpsl** [codeestX/GeekNews#17]
This project does not use the Gradle build system. We recommend that you migrate to using the Gradle build system.意思是我没通过Gradle管理么。直接从github clone下来的。是不是少了什么

**Comment by hrx3627** [comment]
可以的吧。我导入的时候是提示版本错误，下载对应的版本sdk即可。不知道你的是否也是这样的问题

**Comment by codeestX** [comment]
@lpslpsl Hello,我这边导入是没问题的.检查下工程目录有没有缺少gradle相关的文件，重新导入试试看？

**Comment by lpslpsl** [comment]
我重新导入了下。。又可以了。
