### ISSUE TITLE
loss one java file  com.codeest.geeknews.di.component.DaggerAppComponent;

### ISSUE THREAD

**Issue by yygutn** [codeestX/GeekNews#2]
loss one java file  com.codeest.geeknews.di.component.DaggerAppComponent in App.java
![image](https://cloud.githubusercontent.com/assets/8274198/18411957/37feff04-77b6-11e6-93a3-70dac60d5d5d.png)
![image](https://cloud.githubusercontent.com/assets/8274198/18411968/7b78c648-77b6-11e6-90d3-54e6fff03da3.png)

**Comment by codeestX** [comment]
@yygutn Hello yygutn. First, click "Make Project(⌘F9)" in Android Studio. And this file will be created automatically by Dagger2.

**Comment by yygutn** [comment]
@codeestX  thx
