### ISSUE TITLE
程序崩溃，内详

### ISSUE THREAD

**Issue by asdqwc** [codeestX/GeekNews#20]
首次运行程序后在日报里点击任一今日热闻退出程序后再打开程序点击之前点击过的热闻item,程序崩溃，跟踪debug查看貌似是点击item时mPresenter.insertReadToDB(mList.get(position).getId());添加记录时id重复

**Comment by asdqwc** [comment]
@codeestX 这个issue没有上传图片么~想贴log的，对了我的测试机是红米note4 6.0的系统

**Comment by codeestX** [comment]
@asdqwc Hello，感谢反馈.是我之前加了@PrimaryKey注解后没有处理妥当.已经把copyToRealm替换为copyToRealmOrUpdate了
