### ISSUE TITLE
第三方库链接

### ISSUE THREAD

**Issue by autume** [codeestX/GeekNews#23]
你好！widget相关的一些第三方库，能把链接也提供下吗？
如： compile 'com.victor:lib:1.0.4'等未在README中提及的库，谢谢！

**Comment by codeestX** [comment]
@autume Hello, 这个一个loading动画效果的库，新版本里已经不用了，改用SVG动画来实现了，所以从README里去除了. 这个库的地址是[Loading](https://github.com/yankai-victor/Loading)
