### ISSUE TITLE
权限可以考虑RxPermissions

### ISSUE THREAD

**Issue by jp1017** [codeestX/GeekNews#25]
https://github.com/tbruyelle/RxPermissions

**Comment by codeestX** [comment]
@jp1017 好的，我研究下这个库，如果合适的话下个版本就替换成`RxPermissions`

**Comment by jp1017** [comment]
恩，看你RxJava玩的这么6, so, just try it. :smile:

**Comment by codeestX** [comment]
@jp1017 感谢推荐哈 ^ ^
