### ISSUE TITLE
RxJava没有内存泄露吗？

### ISSUE THREAD

**Issue by jp1017** [codeestX/GeekNews#26]
可以考虑RxLifeCycle:

https://github.com/trello/RxLifecycle

分支有 `1.x` 和 `2.x` 对应RxJava 1 和 2.

**Comment by codeestX** [comment]
@jp1017 Hello， 在`RxPresenter`中用`CompositeSubscription`对订阅的生命周期做了处理，所以就没有引入`RxLifeCycle`
