### ISSUE TITLE
apk安装时候的问题

### ISSUE THREAD

**Issue by jackli688** [codeestX/GeekNews#27]
1、将你的项目下载下来，用as向模拟器中烧录，该应用可以安装成功，但是往真机中烧录，那么回报这个错误，Installation failed with message INSTALL_FAILED_UNKNOWN_SOURCES.
It is possible that this issue is resolved by uninstalling an existing version of the apk if it is present, and then re-installing.

WARNING: Uninstalling will remove the application data!

Do you want to uninstall the existing application?
但是，我的手机中之前没有安装过你的应用，这个是怎么回事？
2、通过你留下的apk下载链接，通过电脑下载apk，往真机中安装，结果如下：
C:\Users\Administrator>adb install C:\Users\Administrator\Desktop\geeknews.apk_1.1.0.apk
[100%] /data/local/tmp/geeknews.apk_1.1.0.apk
        pkg: /data/local/tmp/geeknews.apk_1.1.0.apk
Failure [INSTALL_FAILED_UNKNOWN_SOURCES]

**Comment by jp1017** [comment]
重启手机或换个手机试试

**Comment by codeestX** [comment]
@jackli688 Hello，首先确保真机系统在5.0以上，然后去`设置` -> `安全` 中查看下有没有打开`允许安装来自未知来源的应用`

**Comment by jackli688** [comment]
@codeestX,感谢你的回答，我的问题已经解决了。
解决问题的点：
然后去设置 -> 安全 中查看下有没有打开允许安装来自未知来源的应用
非常感谢。
