### ISSUE TITLE
关闭屏幕后一段时间再点亮屏幕时会看到程序被关闭了

### ISSUE THREAD

**Issue by boluomee** [codeestX/GeekNews#30]
关闭屏幕一段时间后（5min以内）再点亮屏幕时会看到程序被关闭了

**Comment by codeestX** [comment]
@hymbo Hello，我这边测了几次没有复现...  方便说下机型么？是必现的么？

**Comment by boluomee** [comment]
红米3s标准版，试过很多次都是同样结果，刚刚发现一点亮屏幕没任何提示就直接退出了，试多次后同样还弹出“GeekNews。要将其关闭吗？”选择对话框。运行时，只开启微信一个应用……

**Comment by codeestX** [comment]
@hymbo 好的，感谢反馈，找到类似的机型后我会去测试下这个问题

**Comment by LyttonDon** [comment]
小米5也出现类似情况，熄屏10S左右点亮，应用卡死。

**Comment by HuuNguyen312** [comment]
Same issue

**Comment by codeestX** [comment]
#85
