### ISSUE TITLE
Dagger2相关

### ISSUE THREAD

**Issue by duchao** [codeestX/GeekNews#31]
@ContextLife("Application")
App getContext();  // 提供App的Context

Activity getActivity();

    @Provides
    @ActivityScope
    public Activity provideActivity() {
        return mActivity;
    }
等等

这些代码没用到吧？
看的很是费解，尤其是ContextLife.java这个不是scope吧，自定义标记的话，文件名看起来好难懂

再提个小bug哈
设置->清除缓存 不能实时更新，清除一次，再浏览网页，产生的缓存就不能清除了

**Comment by codeestX** [comment]
@duchao Hello，这两个`get`方法的确没用到，在`component`中可以不写，`ContextLife`是一个dagger2的`Qualifier`注解，用来给同类型的构造器打Tag来区别的，目前暂时没有用到，也可以不标注的。这个bug我会去看下的，感谢反馈哈

**Comment by duchao** [comment]
作者辛苦！回复很及时！

**Comment by caopeng000** [comment]
****
请问一下，你是怎么切换不同的HOST的，我现在有两个不同的HOST，我使用了和你类似的代码，好像一直只能初始化一个HOST,是不是我还要注意其他的东西。谢谢

**Comment by codeestX** [comment]
Hi @caopeng000 ，我为每个不同的HOST都创建了一个`Retrofit`，用`Qualifier`来区分这些`Retrofit`，可以看下这个类[HttpModule](https://github.com/codeestX/GeekNews/blob/master/app/src/main/java/com/codeest/geeknews/di/module/HttpModule.java)

**Comment by caopeng000** [comment]
这个我知道。我也是这样写的。但是有且只能识别一个，还有其他原因吗

**Comment by codeestX** [comment]
@caopeng000 没有具体代码的话我只能猜原因了..比如依赖的提供方和接收方都要标注相同的`Qualifier`

```
@Singleton
    @Provides
    @VtexUrl
    Retrofit provideVtexRetrofit(Retrofit.Builder builder, OkHttpClient client) {
        return createRetrofit(builder, client, VtexApis.HOST);
    }
```
```
@Singleton
    @Provides
    VtexApis provideVtexService(@VtexUrl Retrofit retrofit) {
        return retrofit.create(VtexApis.class);
    }
```
或者看下Dagger2编译后生成的代码，从里面找原因

**Comment by caopeng000** [comment]
好了。谢谢。没匹配上。提供方写的都是同一个地址
