### ISSUE TITLE
这个不是应用出现问题

### ISSUE THREAD

**Issue by iszengmh** [codeestX/GeekNews#33]
你好，我在学习这个项目的架构，我发现项目BaseActivity中申明了mPresenter，通过在子类重写inject注入P层，但是，我发现在你设计所有module中并没有@Provides提供的P层实例，请问你是怎么设计实现的呢
`/**
 * Created by codeest on 2016/8/2.
 * MVP activity基类
 */
public abstract class BaseActivity<T extends BasePresenter> extends SupportActivity implements BaseView{

    @Inject
    protected T mPresenter;
    protected Activity mContext;
    private Unbinder mUnBinder;

`

**Comment by codeestX** [comment]
@zengmianhui Hello，`dagger2`有两种方式可以提供实例，P层实例是通过`Inject`注解标注构造函数的形式提供的，`RetrofitHelper`和`RealmHelper`实例是通过`Module`+`Provide`注解以工厂的方式提供，两种方式是不同的，可以去看下项目中每个`Presenter`类的构造函数上都有`Inject`注解，这个就是来源

**Comment by iszengmh** [comment]
好的，感谢！
