### ISSUE TITLE
BaseActivity中的mPresenter是在哪里提供依赖的？

### ISSUE THREAD

**Issue by JantHsueh** [codeestX/GeekNews#39]
你好，作者，看了你的代码让我受益匪浅，一个问题想不明白就是在BaseActivity中的mPresenter，是在哪里提供依赖的？？？

`
@ActivityScope
@Component(dependencies = AppComponent.class, modules = ActivityModule.class)
public interface ActivityComponent {

    Activity getActivity();

    void inject(WelcomeActivity welcomeActivity);

    void inject(MainActivity mainActivity);

    void inject(ZhihuDetailActivity zhihuDetailActivity);

    void inject(ThemeActivity themeActivity);

    void inject(SectionActivity sectionActivity);
}
`

在ActivityModule和AppModule中都没有看到提供这个依赖的，

`@Module
public class ActivityModule {
    private Activity mActivity;

    public ActivityModule(Activity activity) {
        this.mActivity = activity;
    }

    @Provides
    @ActivityScope
    public Activity provideActivity() {
        return mActivity;
    }
}`

`@Module
public class AppModule {
    private final App application;

    public AppModule(App application) {
        this.application = application;
    }

    @Provides
    @Singleton
    @ContextLife("Application")
    App provideApplicationContext() {
        return application;
    }

    @Provides
    @Singleton
    RetrofitHelper provideRetrofitHelper() {
        return new RetrofitHelper();
    }

    @Provides
    @Singleton
    RealmHelper provideRealmHelper() {
        return new RealmHelper(application);
    }
}`

我想了半天了，还是没找到为什么是自动实例这个变量，dagger2的demo也看了几个，没有类似的用法。很是困惑，请大神指教一下。谢谢

**Comment by codeestX** [comment]
@JantXue Hello，可以参考 #33

**Comment by JantHsueh** [comment]
@codeestX 谢谢你，回复真快，我刚提问后，翻代码看到了对构造函数的注解，还是Dagger学的不够好，谢谢你
