### ISSUE TITLE
DaggerActivityComponent找不到

### ISSUE THREAD

**Issue by zilingyao** [codeestX/GeekNews#4]
rt

**Comment by codeestX** [comment]
@zilingyao 你好，先build一遍(Make Project)，这个类会由Dagger2自动生成
#2

**Comment by zilingyao** [comment]
好的 多谢

**Comment by CheerQY** [comment]
rebuild了还是找不到怎么办

**Comment by CheerQY** [comment]
DaggerFragmentComponent这个找不到，在相应的包中没有这个类

**Comment by codeestX** [comment]
@CheerQY 问题解决了么？是只有DaggerFragmentComponent找不到还是所有Dagger开头的类都找不到？把build文件夹删掉再Make Project试试看

**Comment by CheerQY** [comment]
@codeestX 我删除了build文件夹，Make project了，还是找不到Dagger开头的类呢
![image](https://cloud.githubusercontent.com/assets/21121962/18654702/cc9723ec-7f15-11e6-85bb-63ac57dcd41c.png)

**Comment by CheerQY** [comment]
不好意思，那些汉字没显示出来，错误如下：
Error:(13, 41) 错误: 找不到符号
符号:   类 DaggerAppComponent
位置: 程序包 com.codeest.geeknews.di.component

**Comment by codeestX** [comment]
@CheerQY 先判断dagger2有没有导入成功吧，能使用dagger2提供的注解么 @Module @Provides 这些

**Comment by superriver** [comment]
运行的时候报错，不能在Android4.4运行

![qq](https://cloud.githubusercontent.com/assets/19811024/19230366/b765b64a-8f06-11e6-95ce-90b67650ee29.png)

**Comment by codeestX** [comment]
@superriver 目前设定的最低版本是5.0以上，没有5.0以上真机的话可以用AS自带的模拟器

**Comment by Spring1901** [comment]
@codeestX  你好.有个问题请教下,,Dagger开头的类都是根据ActivityComponent,AppComponent,FragmentComponent自动生成的,现在我DaggerAppComponent,DaggerActivityComponent都可以正常导入 ,唯独DaggerFragmentComponent一直没办法生成,查看了FragmentComponent,FragmentModule都没有什么问题,重新删除build文件夹重新编译也没有用.理论上不是FragmentComponent,FragmentModule这两个类没有问题,就可以自动生成dagger打头的类文件么?

**Comment by willkernel** [comment]
请参照这篇blog [ Dagger2找不到符号的原因总结](http://blog.csdn.net/z1020573553/article/details/70156810)
