### ISSUE TITLE
请问下为什么不能inject BaseActivity

### ISSUE THREAD

**Issue by qingtenglv** [codeestX/GeekNews#41]
hi，最近看了很多关于dagger2的文章，但还是云里雾里的。
看了这个项目以后请问下为什么如下代码行不通呢？
```
public interface ActivityComponent {
    Activity getActivity();
    void inject(BaseActivity baseActivity);
}
```
方请解惑！thx！

**Comment by codeestX** [comment]
@qingtenglv Hello,Dagger2不支持以注入父类的方式来注入子类，要注入子类只能声明具体的类

在Dagger2的issue中有类似的问题，可以参考[这里](https://github.com/google/dagger/issues/73)

具体注入过程可以去看Dagger2编译阶段生成的`Dagger`开头的类

**Comment by jp1017** [comment]
的确，这是一个坑

**Comment by qingtenglv** [comment]
O(∩_∩)O谢谢回答 我知道了
