### ISSUE TITLE
发现几个程序Crash问题

### ISSUE THREAD

**Issue by LelandACM** [codeestX/GeekNews#52]
1. java.lang.IndexOutOfBoundsException
date = date.substring(0,idx).replace("T"," "); 有可能idx = -1
GoldListAdapter 第91行
TeachAdapter  第58行
索引越界有几个地方，好像是后台的数据格式可能有点不同，偶尔有些日期后面没有个“.” ，所以你
int idx =date.indexOf(".") 可能会等于-1，然后取子串就Crash了。
在取子串之前添加一句判断就ok了
 if (idx > 0) date = date.substring(0, idx).replace("T", " ");

2. Gank福利页面 往下滑的过程中，程序会崩溃
   在GirlFragment 第61行后面添加
 mStaggeredGridLayoutManager.setGapStrategy(StaggeredGridLayoutManager.GAP_HANDLING_NONE);
   //TODO 解决下拉崩溃的临时解决办法 java.lang.IllegalArgumentException: Pixel distance must be non-negative
   //这个BUG已经有人提交给google,暂时解决办法
   //set item prefetch enable false
   mStaggeredGridLayoutManager.setItemPrefetchEnabled(false);

3. x5WebView有的手机使用不了，自动会调用原生的webview
我在google搜索的解决方法是：build.gradle 的defaultConfig添加
 ndk {
            abiFilters"armeabi","armeabi-v7a" , "arm64-v8a","x86","mips"
        }

**Comment by codeestX** [comment]
@GitACDreamer Hi， 问题已修复，感谢反馈
关于第三点，我没有引入`liblbs.so`，所以
ndk {
abiFilters"armeabi","armeabi-v7a" , "arm64-v8a","x86","mips"
}
应该不能解决这个问题，只能自动调用原生`WebView`了
