### ISSUE TITLE
How to show Data when Offline

### ISSUE THREAD

**Issue by HuuNguyen312** [codeestX/GeekNews#54]
Hi

I see your project using Realm to cache. But when offline, I received the notice `Data loading failure ヽ(≧Д≦)ノ`

How to show Data when Offline
Thanks

**Comment by codeestX** [comment]
@ngochuu90
Hello, This application use `OkHttp3` to cache network-data rather than `Realm`.
You can find it in `RealmHelper.java`.
```
builder.addNetworkInterceptor(cacheInterceptor);
builder.addInterceptor(cacheInterceptor);
builder.cache(cache);
```
`Realm` is used to cache reading records and so on.
BTW, Using [RxCache](https://github.com/VictorAlbertos/RxCache) to manage offline data is a better way.

**Comment by codeestX** [comment]
@ngochuu90 Sorry, `RetrofitHelper.java`,  not `RealmHelper.java`.

**Comment by HuuNguyen312** [comment]
I have found `RetrofitHelper`

```
builder.addNetworkInterceptor(cacheInterceptor);
builder.addInterceptor(cacheInterceptor);
builder.cache(cache);


```

When Online 
![screenshot_2017-02-22-15-37-54-776_com codeest geeknews](https://cloud.githubusercontent.com/assets/9895294/23203437/15de6e92-f915-11e6-8ce5-5d1320562ff6.png)

When Offline
![screenshot_2017-02-22-15-38-06-472_com codeest geeknews](https://cloud.githubusercontent.com/assets/9895294/23203441/1baea1fc-f915-11e6-81c2-b3a2b1c4f05f.png)

**Comment by codeestX** [comment]
@ngochuu90 I just had a test in an offline environment with my Nexus6P. And `Zhihu`,`Gank`,`Wechat` modules works well.
`Gold` module load failed. Perhaps because its API does not support `Cache-Control` in `HTTP head`.
`V2EX` module based on `Jsoup` rather than `OkHttp`, it will not work when offline.

**Comment by HuuNguyen312** [comment]
Thanks for your reply. Your information is very helpful. Great Project
