### ISSUE TITLE
有点疑问

### ISSUE THREAD

**Issue by kidcats** [codeestX/GeekNews#56]
、、、
Subscription rxSubscription = mRetrofitHelper.fetchDailyListInfo()
                .compose(RxUtil.<DailyListBean>rxSchedulerHelper())
                .map(new Func1<DailyListBean, DailyListBean>() {
                    @Override
                    public DailyListBean call(DailyListBean dailyListBean) {
                        List<DailyListBean.StoriesBean> list = dailyListBean.getStories();
                        for(DailyListBean.StoriesBean item : list) {
                            item.setReadState(mRealmHelper.queryNewsId(item.getId()));
                        }
                        return dailyListBean;
                    }
                })
                .subscribe(new Action1<DailyListBean>() {
                    @Override
                    public void call(DailyListBean dailyListBean) {
                        topCount = dailyListBean.getTop_stories().size();
                        mView.showContent(dailyListBean);
                    }
                }, new Action1<Throwable>() {
                    @Override
                    public void call(Throwable throwable) {
                        mView.showError("数据加载失败ヽ(≧Д≦)ノ");
                    }
                });
、、、

上面的代码中通过  .compose(RxUtil.<DailyListBean>rxSchedulerHelper())将消费事件切换到了mian主线程，但是从在 item.setReadState(mRealmHelper.queryNewsId(item.getId()));中又进行了数据库查询操作，这样中操作放在主线程中不太妥当吧.....

**Comment by codeestX** [comment]
@kidcats Hello, RealmObject自带线程保护功能，只能在创建它的线程中访问
你可以做个测试，在访问数据库前加上`.observeOn(Schedulers.io())`切到子线程，
在RxJava的错误回调中应该会收到`java.lang.IllegalStateException: Realm access from incorrect thread. Realm objects can only be accessed on the thread they were created.`

[参考这里](http://blog.csdn.net/javine/article/details/51040110)

**Comment by kidcats** [comment]
@codeestX 我做了测试，确实是这样的，thanks：）
