### ISSUE TITLE
项目导入后少了个类

### ISSUE THREAD

**Issue by 995085226** [codeestX/GeekNews#58]
import com.codeest.geeknews.di.component.DaggerFragmentComponent;  找不到这个类

**Comment by codeestX** [comment]
@995085226 Hello，直接编译就好，会自动生成

**Comment by 995085226** [comment]
哇哇哇！！！为什么~~~

**Comment by codeestX** [comment]
`Dagger2`在编译时期生成的代码，可以去了解下这款框架
