### ISSUE TITLE
你好，麻烦问一下你用AndroidStudio哪个版本开发的？

### ISSUE THREAD

**Issue by wcglws** [codeestX/GeekNews#6]
我用2.1.2的怎么提示AS版本问题
![image](https://cloud.githubusercontent.com/assets/16982083/18430295/72ceb2b4-790a-11e6-9a38-96392fac41e3.png)

**Comment by codeestX** [comment]
@wcglws 你好，我用的是2.2.0-rc1， 最新的版本， 你可以将classpath 'com.android.tools.build:gradle:2.2.0-rc1'修改为你的版本
