### ISSUE TITLE
GeekNews App automatically shutdown after a few minutes

### ISSUE THREAD

**Issue by HuuNguyen312** [codeestX/GeekNews#60]
Hi @codeestX 

I noticed that: "GeekNews App automatically turn off after a few minutes (~3-5 minutes)"

```
D/OpenGLRenderer: Flushing caches (mode 1)
D/OpenGLRenderer: PathCache::clear count = 0
D/OpenGLRenderer: Flushing caches (mode 0)
```

How to fix it

**Comment by codeestX** [comment]
Hi @ngochuu90, Thanks for your information. But i'm not sure what caused this problem. 

I will try to reproduce it to collect more info.

**Comment by HuuNguyen312** [comment]
I've been tracking log, but does not see anything unusual. I just found that this log

**Comment by codeestX** [comment]
#85
