### ISSUE TITLE
ActivityModule好像没有什么作用

### ISSUE THREAD

**Issue by kealsoul** [codeestX/GeekNews#64]
ActivityModule用来注入Activity,在项目中好像并没有用到，也许是我没有能理解到其中的作用。

**Comment by codeestX** [comment]
@kealsoul Hi, 目前的确还没用到，考虑到以后扩展Activity级作用域的其他依赖可能会用到这个依赖就一直保留着了，现在忽略就好

**Comment by wangyuan0217** [comment]
我擦， 现在还是没用上吧？   我瞅了半天了
