### ISSUE TITLE
稀土掘金板块和干货集中营

### ISSUE THREAD

**Issue by Yptake** [codeestX/GeekNews#68]
当我快速的刷新再往上拉的时候 稀土掘金板块崩溃 干货板块不能刷新了
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 6(offset:)

**Comment by codeestX** [comment]
@Yptake Hello, 这是一个`RecyclerView`的bug，`notifyItem`系列的方法会触发这个bug，参考[Issue Tracker](https://code.google.com/p/android/issues/detail?id=192106&q=java.lang.IndexOutOfBoundsException%3A%20Inconsistency%20detected.%20Invalid%20item%20position&colspec=ID%20Status%20Priority%20Owner%20Summary%20Stars%20Reporter%20Opened), [StackOverFlow](http://stackoverflow.com/questions/30220771/recyclerview-inconsistency-detected-invalid-item-position)

后面我会做一下处理，感谢反馈
