### ISSUE TITLE
项目导入androud stuido2.3,运行报错

### ISSUE THREAD

**Issue by quanlinzxh** [codeestX/GeekNews#72]
我的as是2.3,gradle版本号:2.14.1,gradle插件2.2.2,导入项目运行后报错:Error:Execution failed for task ':app:transformClassesWithDexForGoogleDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
后来 我加上分包配置: multiDexEnabled true
dependencies {
  compile 'com.android.support:multidex:1.0.0'
}
项目可以正常运行

**Comment by codeestX** [comment]
@quanlinzxh 额.. 这个项目已经引入过`multidex:1.0.1`了，问题解决了就好
