### ISSUE TITLE
项目似乎没有页面状态显示，比如说加载数据时的页面显示，无网络、无数据等状态的显示。可否添加进去，在base进行封装。

### ISSUE THREAD

**Issue by lichun-nick** [codeestX/GeekNews#79]

**Comment by codeestX** [comment]
@lichun-nick Hello，之前是有状态显示的，但是没有封装到base层，加了一层封装[RootActivity](https://github.com/codeestX/GeekNews/blob/master/app/src/main/java/com/codeest/geeknews/base/RootActivity.java) [RootFragment](https://github.com/codeestX/GeekNews/blob/master/app/src/main/java/com/codeest/geeknews/base/RootFragment.java)做状态切换, 如果还需要其他状态可以在这个思路上再扩展
