### ISSUE TITLE
关于presenter设计问题

### ISSUE THREAD

**Issue by fade0706** [codeestX/GeekNews#80]
你好！感谢提供的该开源项目，有以下问题请教
在Contract中定义的Presenter接口和相关方法并继承BasePresenter
而RxPresenter类实现了BasePresenter
而普通的Presenter继承RxPresenter，并去实现Contract中定义的Presenter接口

既然RxPresenter实现了BasePresenter，那为什么还要Contract中定义的Presenter接口去继承BasePresenter，这点没有理解

**Comment by codeestX** [comment]
@GoAheadComeOn Hello，从设计意义上来说，`BasePresenter`约定的是所有`Presenter`都应该具有的特性，无论是`RxPresenter`还是某个`Contract`中的`Presenter`都应该继承来表达出这个关系

举例来说，假如某些场景下，类仅需要继承`RxPresenter`或者仅需要实现`Contract`中的`Presenter`，我也不用做任何修改了，因为它们各自都保留了`BasePresenter`的特性

**Comment by fade0706** [comment]
明白了。。。thinks
