### ISSUE TITLE
下载的项目一切正常，但就在build APK的时候出错，报compileGoogleDebugJavaWithJavac

### ISSUE THREAD

**Issue by BarretWu** [codeestX/GeekNews#81]
项目报compileGoogleDebugJavaWithJavac![9l4t68 f nk1 udrnvl3 d](https://cloud.githubusercontent.com/assets/13414805/25267513/9db8307c-26a7-11e7-9959-40b0b317a495.png)

**Comment by codeestX** [comment]
@BarretWu Hi, 我这边刚试了下是可以打包的, 看下编译的错误日志吧
<img width="446" alt="apk" src="https://cloud.githubusercontent.com/assets/12326467/25311631/fac2c498-2838-11e7-8b27-5bb8c4609d1a.png">

**Comment by Pro47x** [comment]
楼主你是1.8的jdk吗，换成1.7的就ok了
