### ISSUE TITLE
Duplicate Code

### ISSUE THREAD

**Issue by HuuNguyen312** [codeestX/GeekNews#82]
I see in **SimpleFragment** and **BaseFragment** there are many duplicate code

```
    protected View mView;
    protected Activity mActivity;
    protected Context mContext;
    private Unbinder mUnBinder;
    private boolean isInited = false;
```

Why do you not use 

> **BaseFragment**  extends **SimpleFragment**

**Comment by codeestX** [comment]
@ngochuu90 Thank you for your suggestion.
