### ISSUE TITLE
列表滑动卡顿

### ISSUE THREAD

**Issue by weikeet** [codeestX/GeekNews#84]
我使用Android Studio运行出来的GeekNews除了首页知乎日报，其他列表滑动都特别卡。而直接下载apk安装的却不会，这其中的原因是啥？

**Comment by weikeet** [comment]
换成这个版本   compile 'me.yokeyword:fragmentation:0.10.4'   就好了

**Comment by codeestX** [comment]
@lecymeng Hello, 已经升级到了最新的`Fragmentation` 感谢反馈
