### ISSUE TITLE
[Question] How to custom dynamic viewError, viewEmpty

### ISSUE THREAD

**Issue by HuuNguyen312** [codeestX/GeekNews#88]
Hi @codeestX 
My problem: Different fragments have different empty states. How to custom dynamic layout viewEmpty

**Comment by codeestX** [comment]
@ngochuu90 Hi, I had added a new method to custom viewError.

https://github.com/codeestX/GeekNews/blob/master/app/src/main/java/com/codeest/geeknews/base/RootFragment.java#L107-L109

## Usage

```
@Override
    protected void initEventAndData() {
        super.initEventAndData();
        setErrorResource(R.layout.view_error_test);
}
```
And the RootView should be named 'view_error' in ErrorLayoutResource.

**Comment by HuuNguyen312** [comment]
Good job !
