### ISSUE TITLE
[Question] How to inject Presenter

### ISSUE THREAD

**Issue by HuuNguyen312** [codeestX/GeekNews#89]
Hi @codeestX 

I did not find method `void inject (T presenter)` in any of the components. 
I do not understand how to use `@Inject`? For example: 
```
    @Inject
    public GirlPresenter(DataManager mDataManager) {
        this.mDataManager = mDataManager;
    }
```
Thanks!

**Comment by codeestX** [comment]
Hi @ngochuu90 , `@Inject` can annotate a constructor to provide a instance.It can also annotate an object to receive this instance.

For example:
Provider:
```
@Inject
    public GirlPresenter(DataManager mDataManager) {
        this.mDataManager = mDataManager;
    }
```

Receiver:
```
@Inject
    protected T mPresenter;
```

Reference: [Google's Dagger2 Guide](https://google.github.io/dagger/users-guide.html)

**Comment by HuuNguyen312** [comment]
Thanks for your information!
