### ISSUE TITLE
Fragment中的ButterKnife需要unbind

### ISSUE THREAD

**Issue by 3pmTea** [codeestX/GeekNews#9]
翻过ButterKnife的文档和issue，貌似都提到fragment中使用ButterKnife的时候需要调用unbind
http://jakewharton.github.io/butterknife/#reset
https://github.com/JakeWharton/butterknife/issues/291

觉得挺麻烦的，后来我们项目view不多的地方就没用ButterKnife了
up主怎么看？

**Comment by codeestX** [comment]
@3pmTea 你好，没有调用unbind的确是个问题，我会在下个版本修复，感谢反馈

**Comment by jp1017** [comment]
@3pmTea get. :+1: :smile:
