### ISSUE TITLE
服务端返回Http 500错误

### ISSUE THREAD

**Issue by micrologic** [codeestX/GeekNews#92]
当服务端返回Http 500错误的时候，为什么不走 return Flowable.error(new ApiException(tWXHttpResponse.getMsg(), tWXHttpResponse.getCode()));

**Comment by codeestX** [comment]
Hi @micrologic ,Response里的`code`不合法时才会走那里, 单纯的Http错误估计会触发`HttpException`, 尝试在[CommonSubscriber](https://github.com/codeestX/GeekNews/blob/master/app/src/main/java/com/codeest/geeknews/widget/CommonSubscriber.java)的`onError`里处理错误
