### ISSUE TITLE
InitializeService去初始化日志、bugly、内存检测等好像没有设置成功。

### ISSUE THREAD

**Issue by kealsoul** [codeestX/GeekNews#97]
直接在application里面设置可以成功。

**Comment by codeestX** [comment]
Hi @kealsoul，我测试过日志和bugly是可用的，内存检测最近没测过，用的时候要自己添加[RefWatcher](https://github.com/square/leakcanary/wiki/FAQ#how-do-i-use-it)

**Comment by caopeng000** [comment]
InitializeService 没有在manifest.xml中注册啊怎么做到的
