### ISSUE TITLE
关于内存泄露的问题

### ISSUE THREAD

**Issue by caopeng000** [codeestX/GeekNews#98]
hi，哥们还是我，哈哈。想问你个关于内存泄露的问题，如果在网络请求还没有返回的时候，界面退出，有可能会造成空指针异常。实例：ThemeChildPresenter
`@Override
    public void getThemeChildData(final int id) {
        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                addSubscribe(mDataManager.fetchThemeChildListInfo(id)
                        .compose(RxUtil.<ThemeChildListBean>rxSchedulerHelper())
                        .map(new Function<ThemeChildListBean, ThemeChildListBean>() {
                            @Override
                            public ThemeChildListBean apply(ThemeChildListBean themeChildListBean) {
                                List<ThemeChildListBean.StoriesBean> list = themeChildListBean.getStories();
                                for (ThemeChildListBean.StoriesBean item : list) {
                                    item.setReadState(mDataManager.queryNewsId(item.getId()));
                                }
                                return themeChildListBean;
                            }
                        })
                        .subscribeWith(new CommonSubscriber<ThemeChildListBean>(mView) {
                            @Override
                            public void onNext(ThemeChildListBean themeChildListBean) {
                                Log.i("TAG", "----主题界面的请求回调onNext");
                                mView.showContent(themeChildListBean);
                            }
                        })
                );
            }
        }, 1000);

    }`

我给网络请求延迟了1秒，然后我进去界面马上退出，然后网络请求回调成功后，调用showContent，然后就崩溃了。对于这种情况需要做特殊处理吗，比如判断mView！=null

**Comment by codeestX** [comment]
@caopeng000 Hi，这种情况应该是Handler造成的泄漏导致这次`addSubscribe`在`RxPresenter`的`unSubscribe();`之后执行了，所以订阅没被清掉。可以用`mView！=null`做特殊处理，不过最好避免泄漏从根源上解决问题..

**Comment by caopeng000** [comment]
恩恩，老铁没毛病。哈哈
